/**
 * /connections endpoint tests
 *
 * Validates route availability between chains/tokens.
 * Not cached — results are param-dependent.
 *
 * In addition to the deterministic baseline tests below, an agentic block
 * loads AI-generated scenarios from `mcp/generated-scenarios.json` via
 * `getAgentScenarios('/connections')`.
 */

import { test, expect } from '@playwright/test';
import { LiFiApiClient } from '../helpers/api-client';
import { assertOk, assertResponseTime } from '../helpers/assertions';
import { CHAINS, TOKENS } from '../helpers/test-data';
import { getAgentScenarios } from '../helpers/agentic-scenarios';

test.describe('/connections endpoint', () => {
  let client: LiFiApiClient;

  test.beforeEach(({ request }) => {
    client = new LiFiApiClient(request);
  });

  test.describe('basic response', () => {
    test('returns connections for Polygon -> Arbitrum', async () => {
      const start = Date.now();
      const { response, data } = await client.getConnections({
        fromChain: CHAINS.POLYGON,
        toChain: CHAINS.ARBITRUM,
      });
      assertOk(response);
      assertResponseTime(start, 5000);
      expect(data).toBeDefined();
    });

    test('returns connections with token filter', async () => {
      const { response, data } = await client.getConnections({
        fromChain: CHAINS.POLYGON,
        toChain: CHAINS.ARBITRUM,
        fromToken: TOKENS.USDC_POLYGON,
      });
      assertOk(response);
      expect(data).toBeDefined();
    });

    test('same chain connections are returned', async () => {
      const { response } = await client.getConnections({
        fromChain: CHAINS.POLYGON,
        toChain: CHAINS.POLYGON,
      });
      // Same-chain swaps are valid (DEX aggregation)
      expect([200, 400]).toContain(response.status());
    });
  });

  test.describe('parameter validation', () => {
    test('returns error for invalid fromChain', async ({ request }) => {
      const response = await request.get(
        'https://li.quest/v1/connections?fromChain=INVALID&toChain=42161'
      );
      expect(response.status()).not.toBe(500);
    });

    test('handles missing parameters gracefully', async ({ request }) => {
      const response = await request.get('https://li.quest/v1/connections');
      // Should return all connections or a 400 — not a 500
      expect(response.status()).not.toBe(500);
    });
  });

  // -- Agentic scenarios -----------------------------------------------------
  // Loaded from mcp/generated-scenarios.json (regenerated by `npm run scenarios`).
  // Falls back to an empty array if the file is missing — no hard failures.

  test.describe('agentic scenarios', () => {
    const scenarios = getAgentScenarios('/connections');

    if (scenarios.length === 0) {
      test('no agentic scenarios available (skipped)', async () => {
        console.log('No /connections agentic scenarios found — run `npm run scenarios` to generate them.');
      });
    }

    for (const s of scenarios) {
      test(s.name, async () => {
        const { response } = await client.getConnections(
          s.params as Parameters<LiFiApiClient['getConnections']>[0]
        );

        expect(
          s.expectedStatus,
          `Unexpected HTTP ${response.status()} for scenario "${s.name}". Notes: ${s.notes}`
        ).toContain(response.status());
      });
    }
  });
});
